all: serveur1-404NotFound serveur2-404NotFound serveur3-404NotFound

serveur1-404NotFound: serveur1-404NotFound.c
	gcc serveur1-404NotFound.c -o ../bin/serveur1-404NotFound

serveur2-404NotFound: serveur2-404NotFound.c
	gcc serveur2-404NotFound.c -o ../bin/serveur2-404NotFound

serveur3-404NotFound: serveur3-404NotFound.c
	gcc serveur3-404NotFound.c -o ../bin/serveur3-404NotFound

clean:
	\rm -rf *.o *~